const header = (req,res)=>{
    res.send(
        {
            home: "Home",
            bolly: "Bollywood",
            techno: "Technology",
            holly: "Hollywood",
            fit: "Fitness",
            food: "Food",
            the: "The",
            siren: "Siren",
            theLatest:"The Latest",
            lastArt: "Latest Articles",
            adv:"Advertistement",
            vMore: "VIEW MORE",
            post: "Top Post",
            one: "1",
            two: "2",
            three: "3",
            four: "4",
            sub1: "Catch Waves with",
            sub2: "an adventure guide",
            info: "Gujarat is vastly underrated and it’s a mystery to us why the region isn’t more well-known as a tourist destination. It has a plethora of temples and palaces",
            subh1: "TECH",
            subh2: "STYLE ",
            date: "/ TODAY AT 11:54",
            btnName: "Get Started",
            followers: "9.3K",
            shareArt: "Share this article",
            fivehead: "5 Ways to animate a React app.",
            userName: "Dmitry Nozhenko",
            userRead: "Jan 28, 2019 10 min read",
            contImgText: "Animation in ReactJs app is a popular topic and there are many ways to create different types of animations.Many developers create animation exclusively using css and adding classes to HTML tags. This is a great way and you should use it. If you want to create complex animations you can pay attention to GreenSock. GreenSock is the most powerful animation platform. There are also a lot of libraries, components for creating animation in React.",
            talk: "Let’s talk about them",
            react: "React",
            js: "JavaScript",
            ani: "Animation",
            clap: "Clap",
            authInfo: "WRITTEN BY",
            authName: "Dmitry Nozhenko",
            authDat: "Jan 28, 2019 · 10 min read",
            mSiren: "More From The Siren",
            tagged: "Also tagged ReactJs",
            tree: "Joshua Tree Overnight Adventure",
            augdate: "Aug 10 . 4 min read",
            authText: "Performance Comparison for 5 JavaScript Object Iterations",
            imgOne: "https://ibb.co/P6T0H55",
            imgTwo: "https://drive.google.com/file/d/1wnSBM11L2rysn2WPnns1aSqeCa7OHJrh/view?usp=share_link"
        },
    )
}

module.exports.headerData = header;